version: 2
updates:

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    groups:
      python-packages:
        patterns:
          - "*"
    pull-request-branch-name:
      separator: "-"
    labels:
      - "dependencies"
      - "python"
    reviewers:
      - "stilkin-pxl"
